---

cluster_name: 'Test Cluster'
hinted_handoff_enabled: true

# Directories to set
hints_directory: '/var/lib/cassandra/hints'
data_file_directories: '/var/lib/cassandra/data'
commitlog_directory: '/var/lib/cassandra/commitlog'
saved_caches_directory: '/var/lib/cassandra/saved_caches'

# Authentication
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer

# IP
# Setting listen_address to 0.0.0.0 is always wrong.
listen_address: 0.0.0.0
rpc_address: 0.0.0.0
# If rpc_address is set to 0.0.0.0, broadcast_rpc_address must set
broadcast_rpc_address:

# type of snitch
#  - GossipingPropertyFileSnitch
#    This should be your go-to snitch for production use.  The rack
#    and datacenter for the local node are defined in
#    cassandra-rackdc.properties and propagated to other nodes via
#    gossip.  If cassandra-topology.properties exists, it is used as a
#    fallback, allowing migration from the PropertyFileSnitch.
endpoint_snitch: GossipingPropertyFileSnitch
